### ISSUE TITLE
HMM for multiple bursts

### ISSUE THREAD

**Issue by bniebuhr** [TheoMichelot/moveHMM#14]
Hey there,

I understand that a central assumption of HMM is that one needs regular data to be analyzed - gaps are not allowed. Depending on the tracking device, environment etc., there may be great irregularities in data sampling. One possibility to deal with that is to fill these gaps through interpolation, but it can generate serious biases, mainly if the gaps are large.

Another way is to separate individual movement into subtracks or bursts and perform the analyses ignoring those gaps - one considers only the sets of timestamps for which the sampling is regular e continuous. Is it possible to accommodate bursts  in `moveHMM` analyses, but still considering each burst as part of the path of the same animal?

This question may be related this [other one](https://github.com/TheoMichelot/moveHMM/issues/13), since analyses for several individuals and several bursts may be similar, but I thought it was better to write a separate issue.

**Comment by TheoMichelot** [comment]
Dear Bernardo,

Indeed, the locations should be observed at regular time intervals. It is also possible to have gaps in an otherwise regular time grid. In moveHMM, such gaps should be indicated by rows of NAs in the data frame. The derivation of the likelihood function in the presence of missing values is explained in the section "_Estimation, decoding, model selection, and model checking_" of Langrock et al., 2012.

Missing covariates are a problem, however, and they need to be interpolated somehow. By default, moveHMM copies the previous value if a covariate is missing. (It also prints a warning message when that happens.) This is not a good method if there are many missing values.

You can also split the track where there are long gaps. Each subtrack should then be identified by a different ID. If you fit a model to the subtracks, one set of parameters will be estimated for them all, which is appropriate if they come from the same animal.

Best wishes,
Théo

References:
 - Langrock et al. (2012). Flexible and practical modeling of animal telemetry data: hidden Markov models and extensions. Ecology, 93(11), 2336-2342.

**Comment by bniebuhr** [comment]
Dear Théo,

> Indeed, the locations should be observed at regular time intervals. It is also possible to have gaps in an otherwise regular time grid. In moveHMM, such gaps should be indicated by rows of NAs in the data frame. The derivation of the likelihood function in the presence of missing values is explained in the section "_Estimation, decoding, model selection, and model checking_" of Langrock et al. (2012).

Great! I'll take a look at that.

> Missing covariates are a problem, however, and they need to be interpolated somehow. By default, moveHMM copies the previous value if a covariate is missing. (It also prints a warning message when that happens.) This is not a good method if there are many missing values.

Ok. Missing covariates is not the problem here - the issue is missing timestamps (and correspondent locations), so, no problems with that.

> You can also split the track where there are long gaps. Each subtrack should then be identified by a different ID. If you fit a model to the subtracks, one set of parameters will be estimated for them all, which is appropriate if they come from the same animal.

Great, that answers my question. I think I can use the subtracks then.
Thanks!

Best,
Bernardo
