### ISSUE TITLE
model fitting problem

### ISSUE THREAD

**Issue by faridcher** [TheoMichelot/moveHMM#2]
When I try to fit the model using the following initial parameters (similar to the help page) and fitting the model I get an error:
```
# Params
stepDist <- "gamma"
angleDist <- "vm"
nbStates <- 2
angleMean <- c(pi,0)

mu0 <- c(1,4)
sigma0 <- c(2,3)
kappa0 <- c(1,1)
stepPar0 <- c(mu0,sigma0) # no zero-inflation, so no zero-mass included
anglePar0 <- kappa0 # the angle mean is not estimated, so only the concentration parameter is needed

m <- fitHMM(formula=~1,
            data=prep,nbStates=nbStates,stepPar0=stepPar0,
            anglePar0=anglePar0,stepDist=stepDist,
            angleDist=angleDist,angleMean=angleMean)

```

I get this error:

> Error in fitHMM(formula = ~1, data = prep, nbStates = nbStates, stepPar0 = stepPar0,  : 
>   Wrong number of initial parameters -- there should be 6 initial step parameters -- zero-mass parameters should be included

I change stepPar0 to:
`stepPar0 <- c(mu0,sigma0,1,1) `
The fitting process take places but when I want to `plot(m)` , it give another error and doesn't plot the results:

> Decoding states sequence... 
> Error in stSeq[nbObs] <- which.max(xi[nbObs, ]) : 
>   replacement has length zero

**Comment by TheoMichelot** [comment]
Hi,

Note that zero-mass parameters are between 0 and 1, and are typically much closer to zero (otherwise, it means that you have many steps of length 0). So, choosing (1,1) as initial zero-mass parameters might not be ideal; you could try e.g. (0.01,0.01), for 1% of steps of length 0 in each state.

It is hard to know what causes the error that you encountered, but I suspect that the optimizer did not converge to any meaningful model, because of the choice of initial parameters. Thus, I would recommend that you try other sets of initial parameters. You might need to adapt the other initial parameters as well (means and standard deviations of the step and angle distributions).

I hope that this helps. If you still get the same error, please send the output of `print(m)`.

Théo

**Comment by faridcher** [comment]
I think the optimizer has converged, because printing the model gives meaningful results:

**Comment by TheoMichelot** [comment]
You can see that the value of the maximum log-likelihood is very negative. For R, it actually stands for minus infinity, meaning that the maximum likelihood is essentially zero, and this is not very good sign.
Besides, printing the model should output the maximum likelihood estimates. However, in the output you show, the printed values are the initial parameters you chose. This means that the optimizer did not depart from the initial values, because it was in a very flat region of the likelihood. If you use the option verbose=2 in fitHMM, you will probably notice that the optimizer only runs one iteration, and stops because it fails to find a higher point.

So, I would recommend trying different initial parameter values. The mean/sd/concentration parameters should be chosen appropriately for your data.

**Comment by faridcher** [comment]
The problem was with the initial values for step-length parameters; this was causing the optimization routine to fail. I am analyzing a migratory bird so the parameters to adapt its movement are as follows:

```R
mu0 <- c(1,1) #(state1,state2)
sigma0 <- c(50,30) #(state1,state2)
zero_mass0 <- c(0,1)
#if we have duplicates (step-length zero) the first zero_mass should not be zero
stepPar0 <- c(mu0,sigma0,zero_mass0) # no zero-inflation, so no zero-mass included
```

**Comment by TheoMichelot** [comment]
This is an old post, but in case anyone still finds it when looking for guidance about numerical problems: there is a vignette in moveHMM about choosing good initial parameter values (stepPar0 and anglePar0).

https://cran.r-project.org/web/packages/moveHMM/vignettes/moveHMM-starting-values.pdf
