### ISSUE TITLE
problem with other distributions

### ISSUE THREAD

**Issue by DanaKarelus** [TheoMichelot/moveHMM#6]
Hello Théo, 

While trying to test HMMs with different distributions in moveHMM (using GPS data), we came across a problem. The gamma distribution worked ok, but the exponential and Weibull distributions aren't working properly.

Here is a simplified reproducible example using created data and the exponential distribution:

```
library(moveHMM)

test <- function(gamma.mean=1,gamma.sd=1,seed=101) {
    if (!is.null(seed)) set.seed(seed)
    n <- 5000
    ## mean=shape*scale; var=shape*scale^2; sd = sqrt(shape)*scale
    ## scale = sd^2/mean; shape = (mean/sd)^2
    gamma.scale <- gamma.sd^2/gamma.mean
    gamma.shape <- (gamma.mean/gamma.sd)^2
    fakedata <- data.frame(ID=factor(1),
                       step=rgamma(n,gamma.shape,scale=gamma.scale),
                       angle=rvm(n,0,0.5)-pi)
    class(fakedata) <- c("moveData","data.frame")
    fit <- fitHMM(data=fakedata,
                  nbStates=1,
                  stepPar0=10,
                  anglePar0=c(0,pi),
                  stepDist="exp",
                  formula=~1)
    ok <- fit$mod$iterations>0
    result <- c(scale=gamma.scale,shape=gamma.shape,
                mean=mean(fakedata$step),sd=sd(fakedata$step),
                fit=ok)
    return(result)
}

test(1,1) ## ok
test(150,175) ## not ok
```

Thank you for your help,
Dana

**Comment by TheoMichelot** [comment]
Hi Dana,

It seems that the problem is your choice for the initial rate parameter of the exponential distribution. The convergence of the optimiser to the global maximum of the likelihood (and thus to the maximum likelihood estimates) depends on the choice of the initial parameter values. We discuss this a little in Section 3.2.2 of the vignette. 

For example, you could try `stepPar0=0.1` in your second example. 

I hope this helps. Let me know if you still have any trouble with this.

Best wishes,
Théo

**Comment by DanaKarelus** [comment]
Hi Théo, 

Thank you for your help! 
I see now where you say on page 16, "The gamma distribution expects the mean and standard deviation, and all other distributions expect the same parameters as the corresponding R density function, i.e." 

I had looked at that page, but somehow that detail escaped me and I thought I was supplying the mean (as in the gamma, just without the variance). 

Thank you,
Dana
